### ISSUE TITLE
A field update command that could turn on the encrypted flag?

### ISSUE THREAD

**Issue by KeithClarke** [mshanemc/shane-sfdx-plugins#9]
Hi Shane,

I have a need described here [Is there an SFDX plugin that allows an existing field to be updated available somewhere?](https://salesforce.stackexchange.com/questions/238869/is-there-an-sfdx-plugin-that-allows-an-existing-field-to-be-updated-available-so) that looks close to one of your existing commands (sfdx shane:object:field). If you do add that support in the future, do let me know.

Thanks,
Keith

**PS**

Looking at the source, the "shane:object:field" command appears to be a "local source" one whereas I'm looking for an org modification.

**Comment by mshanemc** [comment]
If I'm understanding, you're trying to test across lots of configurations, but want to modify those through commands instead of having a bazillion source variations.

I'm definitely building local source (and then you can push/deploy/convert/package depending on where  you're trying to go).  Directly modifying the org is not what I'm wanting to do.

I'd suggest something like what my command shares (getExisting from xml, convert to json, change something (like in this case the encryptedness) and then write back to xml.

So it's modifying source, probably before push/deploy but that change never gets checked in anywhere.

I think I'd still prefer a branch for each configuration rather than commands doing all this in scripts.  

If trying to maintain those branches is the problem, then a script to autogenerate them from "master" might be a good approach.  So you'd have "master, but encrypted" regenerated each time master changes in some other way?

Cool problem!

**Comment by KeithClarke** [comment]
Thanks for taking a look. I hadn't noticed the "Modifies local source--you still need to push/deploy" that is present on lots of the commands but wasn't present on that one. I agree what I was looking for doesn't fit with your plugins or for that matter (probably) the SFDX framework. As sometimes we want the encryption setting up for customers too, I'll probably go for doing the setup from Apex via https://github.com/financialforcedev/apex-mdapi: I can then just execute the Apex via SFDX.

**Comment by mshanemc** [comment]
Good luck...definitely an interesting approach for me whenever I need something like that (on the fly metadata modifications outside of source)
